### ISSUE TITLE
Pipx and caching

### ISSUE THREAD

**Issue by fredrikaverpil** [fredrikaverpil/setup-pipx#8]
If caching is enabled, like in the advanced example, the `../pipx_venv` should not be created. Only the `$PATH` should be updated, so the pipx-installed binaries can be found.

Or, more likely, might want this order instead:

```yml
      - uses: fredrikaverpil/setup-pipx@v1.3
        with:
          pipx-version: "1.0"

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry/virtualenvs
            ../pipx_venv
            ~/.local/bin
            ~/.local/Scripts
          key: ${{ runner.os }}-py-${{ matrix.python-version }}-pipx-${{ matrix.pipx-version }}-poetry-${{ matrix.poetry-version }}-${{ hashFiles('poetry.lock') }}

```
